### ISSUE TITLE
Consistent Crash Upon Initial Handler Replacement

### ISSUE THREAD

**Issue by nin-ack** [GoSecure/frida-xamarin-unpin#1]
Hey there- having some issues getting it working successfully.

Everything appears fine **until the first actual interaction with the application and first handler replacement where the application crashes**.

**Device:** `Pixel XL2`
**Emulated via Genymotion:** `Android 8.0`
**Genymotion:** `Version 3.0.4 | Revision 20191213-90e54e2`
**Genymotion Version:** `12.8.19`

**Host Machine:** `OSX Mojave 10.14.6`
**Frida Version:** `12.8.19`

![image](https://user-images.githubusercontent.com/16235213/78628038-a3df5880-7858-11ea-8496-0206a9fc48e9.png)

```
[+] Created Default HttpClientHandler @ 0xd0f3c740
[+] Hooked HttpMessageInvoker.SendAsync with DefaultHttpClientHandler technique
[-] ServicePointManager validation callback not found.
[+] Done!
Make sure you have a valid MITM CA installed on the device and have fun.
[Google::com.application.test]-> [*] HttpClientHandler.SendAsync called
[+]   Replaced with default handler @ 0xd0f3c740
[*] HttpClientHandler.SendAsync called
[+]   Replaced with default handler @ 0xd0f3c740
Process terminated
```

**Comment by alxbl** [comment]
Good catch, it looks like I forgot to repackage the pre-built script after fixing that bug.

The reason this happens is because the application is using multiple HTTP client instances, and the initial script had a bug which would allocate the same handler to all clients... When one client gets disposed, the handler gets disposed as well, and other clients will throw an exception.

I'm going to repackage the pre-built script.

**Comment by alxbl** [comment]
I've updated the script in `dist/`. If you still have crashes, let me know.
