### ISSUE TITLE
access violation error. 

### ISSUE THREAD

**Issue by AkshayJainG** [GoSecure/frida-xamarin-unpin#3]
I am running this on Android 5.1 version.
 Any idea why is it showing Error: access violation?  

frida -U -l xam.js com.test
     ____
    / _  |   Frida 12.8.20 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://www.frida.re/docs/home/
Attaching...
[+] Hooked HttpMessageInvoker.SendAsync with DefaultHttpClientHandler technique
[-] ServicePointManager validation callback not found.
[+] Done!
Make sure you have a valid MITM CA installed on the device and have fun.
[Nexus 4::com.linde.limang]-> [*] HttpClientHandler.SendAsync called
Error: access violation accessing 0x0
    at FieldGetValueObject (/xam.js:122)
    at onEnter (/xam.js:2834)
[*] HttpClientHandler.SendAsync called
Error: access violation accessing 0x0
    at FieldGetValueObject (/xam.js:122)
    at onEnter (/xam.js:2834)
Process terminated

**Comment by alxbl** [comment]
Hey, this is unusual. Did you customize the script in any way or are you using the pre-built one from `dist/`?

Can you give me the version of Mono that is mapped in memory? It looks like either the HttpClientHandler that was hooked got garbage collected or the `_handler` field doesn't exist in your version of Mono.

I don't have access to a test setup right now since my hardware is at the office, but I'll check when I have a chance.

----

To get some debugging information on your end, you can try to add a line at line 2833 that prints `handler` and `self`.

**Comment by achmstein** [comment]
Hello,

I printed handler and self and I got the following lines in console window

[*] HttpClientHandler.SendAsync called
**0x7ee3bed850
0x0**
Error: access violation accessing 0x0
    at FieldGetValueObject (mono-api/src/mono-api-helper.js:54)
    at onEnter (src/main.js:56)

**Comment by achmstein** [comment]
@alxbl  How to know the version f Mono mapped in memory?

**Comment by alxbl** [comment]
You can enumerate the loaded modules with Frida and look for the mono runtime library. It should have a version number (usually `mono` or `libmonosgen`). You can also unpack the APK and look at what is packaged with it.

I'm not sure why `self` would be NULL when you enter `SendAsync`, it could be a race condition or a version quirk.

I don't have access to the phone I did the tests on due to the COVID-19 lockdown, so I'm not going to be able to dive into debugging this for a while.
